[project]
name = "ai-coach"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mauryaraheja", email = "mraheja_be24@thapar.edu" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
personaltracker = "personaltracker:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
