"""
Market validation: search real, live job postings for a role and extract
the technical skills actually mentioned in them, then compare that
against the LLM-generated roadmap to surface skills the roadmap might be
missing (or skills it has that this batch of postings doesn't back up).

Deliberately NOT wired into get_or_create_roadmap()'s cache-or-generate
flow. The roadmap is evergreen and correctly cached in SQLite; job
postings go stale in weeks, not months, so mixing the two into one
cached object would misrepresent how fresh the market data actually is.
This runs as an explicit, separate action instead (see app.py).

Only pulls from company ATS pages and job boards with no login wall and
no scraping-enforcement history (Greenhouse, Lever, Indeed, Wellfound).
LinkedIn and Glassdoor are deliberately excluded -- having Tavily fetch
their pages on our behalf raises the same ToS/consent problem as
scraping them directly.
"""

import json
from .clients import groq_client, tavily_client
from .roadmap import refine_role

MARKET_DOMAINS = ["greenhouse.io", "lever.co", "indeed.com", "wellfound.com"]


def search_job_postings(role: str, max_results: int = 8) -> list[dict]:
    """Fetch real, live job postings for a role -- not skill roundup
    articles, actual posting pages. Higher max_results than
    roadmap.search_job_info's 5, since frequency counts need a slightly
    larger sample to mean anything."""
    response = tavily_client.search(
        query=f"{role} job posting requirements qualifications",
        max_results=max_results,
        search_depth="advanced",
        include_domains=MARKET_DOMAINS,
    )
    return response.get("results", [])


def format_postings_for_prompt(postings: list[dict]) -> str:
    """Turn raw postings into text the LLM can read, one block per posting."""
    blocks = []
    for p in postings:
        snippet = p.get("content", "")[:1500]
        blocks.append(f"Source: {p.get('url')}\n{snippet}")
    return "\n\n".join(blocks)

def extract_skills_from_posting(role: str, posting: dict) -> list[str]:
    """
    Extract technical skills from ONE job posting.
    Returns only skill names.
    """

    prompt = f"""
    This is ONE real job posting for the role: {role}

    URL:
    {posting.get("url")}

    Content:
    {posting.get("content", "")[:3000]}

    Extract every specific technical skill, framework, library,
    platform, database, cloud service, programming language,
    or tool explicitly mentioned.

    Do NOT infer missing skills.

    Return JSON only.

    {{
        "skills": [
            "PyTorch",
            "Spark",
            "AWS"
        ]
    }}
    """

    response = groq_client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        print("Invalid JSON while extracting posting skills.")
        print(raw)
        return []

    return data.get("skills", [])

def extract_market_skills(role: str, postings: list[dict]) -> list[dict]:
    """
    Extract skills from each posting individually.

    Temporary version:
    Returns raw skill mentions before consolidation.
    """

    raw_mentions = []

    for posting in postings:

        skills = extract_skills_from_posting(role, posting)

        print(f"\n{posting['url']}")
        print(skills)

        for skill in skills:
            raw_mentions.append(
                {
                    "skill_name": skill,
                    "source_url": posting["url"],
                }
            )

    print("\n========== RAW MENTIONS ==========")
    print(raw_mentions)

    return raw_mentions


def compare_to_roadmap(roadmap_skills: list[dict], market_skills: list[dict]) -> dict:
    """Compare the LLM-generated roadmap against skills actually found in
    real job postings. Single call across the whole roadmap -- same
    reasoning as gap_analysis.get_skill_gaps: cheap at this scale, and
    lets the model reason about near-duplicate names consistently
    instead of skill-by-skill."""

    roadmap_text = "\n".join(
        f"- id: {s['id']}, name: {s['name']}" for s in roadmap_skills
    )
    market_text = "\n".join(
        f"- {m['skill_name']} (mentioned in {m['mention_count']} postings)"
        for m in market_skills
    )

    prompt = f"""
    Roadmap skills (generated by an LLM from general web sources):
    {roadmap_text}

    Skills actually found in real job postings for this role:
    {market_text}

    Match these two lists semantically -- the same skill may be named
    differently in each. Use your judgment on whether two names are
    close enough to count as a match.

    Return a JSON object with exactly these three keys:

    "confirmed": roadmap skills a market skill backs up. List of objects
    with "roadmap_skill_id", "roadmap_skill_name", "matched_market_skill",
    "mention_count".

    "suggested_additions": market skills with no close match in the
    roadmap -- real skills employers ask for that the roadmap is missing.
    List of objects with "skill_name", "mention_count", "source_urls".

    "weak_signal": roadmap skills with no market skill backing them up.
    This does NOT mean they're wrong -- postings often omit foundational
    or assumed skills -- just that this batch didn't confirm them. List
    of objects with "roadmap_skill_id", "roadmap_skill_name".

    Respond with JSON only, no extra text.
    """

    response = groq_client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"},
    )

    raw_text = response.choices[0].message.content

    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError:
        print("The model didn't return valid JSON. Raw response:")
        print(raw_text)
        return {"confirmed": [], "suggested_additions": [], "weak_signal": []}

    return data


def get_market_validation(role: str, roadmap_skills: list[dict]) -> dict:
    """Full pipeline: refine the role, pull real postings, extract skills
    actually asked for, compare against the existing roadmap. Called
    explicitly from the UI -- not part of get_or_create_roadmap()."""

    refined_role = refine_role(role)

    postings = search_job_postings(refined_role)
    if not postings:
        print("Warning: no job postings found -- market validation skipped.")
        return {
            "confirmed": [],
            "suggested_additions": [],
            "weak_signal": [],
            "market_skills": [],
            "total_postings_scanned": 0,
        }

    market_skills = extract_market_skills(refined_role, postings)
    comparison = compare_to_roadmap(roadmap_skills, market_skills)
    comparison["market_skills"] = market_skills
    comparison["total_postings_scanned"] = len(postings)

    return comparison